name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Create service account file
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > serviceAccount.json

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project el-mostashar2026 --token "${{ secrets.FIREBASE_TOKEN }}"
